# Run the project's test suite
name: Tests

on:
  push:
    branches:
    - master
    - main
    - '*.x'
  pull_request:
    branches:
    - master
    - main
    - '*.x'

jobs:
  test:
    name: Test Python ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.10']
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Print basic Python info
      shell: python
      run: |
        import sys
        print(sys.executable, sys.version, sep='\n')
    - name: Install baseline deps
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install build deps
      run: python -m pip install --upgrade --upgrade-strategy eager build pip setuptools wheel
    - name: Build package
      run: python -bb -X dev -W error -m build
    - name: Install wheel
      shell: bash
      run: 'echo dist/*.whl | xargs -I % python -bb -X dev -W error -W ignore::DeprecationWarning:pip._internal.locations._distutils -W ignore::DeprecationWarning:distutils.command.install -m pip install --upgrade %[test]'
    - name: List packages in environment
      run: pip list
    - name: Install Chromium
      run: python -m playwright install chromium
    - name: Run tests
      shell: bash
      run: python -I -bb -X dev -W error -m pytest --compare-screenshots
    - name: Upload UI Test artifacts
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: visual-regression-test-output-${{ matrix.os }}
        path: |
          docrepr/tests/references/**
          docrepr/tests/screenshots/**
          docrepr/tests/diffs/**
    - name: Twine check
      run: pipx run twine check --strict dist/*
    - name: Pip check
      run: pip check -v
