name: Update references

on:
  issue_comment:
    types: [created, edited]


jobs:
  update_references:

    name: PR comment
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'Please generate reference screenshots') }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout the branch from the PR that triggered the job
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Print basic Python info
        shell: python
        run: |
          import sys
          print(sys.executable, sys.version, sep='\n')
      - name: Install docrepr
        run: python -m pip install --upgrade .[test]
      - name: List packages in environment
        run: pip list
      - name: Install Firefox
        run: python -m playwright install firefox
      - name: Run tests
        shell: bash
        run: python -I -bb -X dev -W error -m pytest --generate-reference-screenshots
      - name: Commit reference images
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git add docrepr/tests/references

          git commit -m "Update references"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
