name: Update references

on:
  issue_comment:
    types: [created, edited]


jobs:
  update_references:

    name: PR comment
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'Please generate reference screenshots') }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.10']
    steps:

      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Print basic Python info
        shell: python
        run: |
          import sys
          print(sys.executable, sys.version, sep='\n')
      - name: Install baseline deps
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install build deps
        run: python -m pip install --upgrade --upgrade-strategy eager build pip setuptools wheel
      - name: Build package
        run: python -bb -X dev -W error -m build
      - name: Install wheel
        shell: bash
        run: 'echo dist/*.whl | xargs -I % python -bb -X dev -W error -W ignore::DeprecationWarning:pip._internal.locations._distutils -W ignore::DeprecationWarning:distutils.command.install -m pip install --upgrade %[test]'
      - name: List packages in environment
        run: pip list
      - name: Install Firefox
        run: python -m playwright install firefox
      - name: Run tests
        shell: bash
        run: python -I -bb -X dev -W error -m pytest --generate-reference-screenshots
      - uses: EndBug/add-and-commit@v8
        with:
          add: docrepr/tests/references
          push: origin ${GITHUB_REF##*/}
          message: 'Update references'
