# Run the project's test suite
name: Visual Regression Tests

on:
  push:
    branches:
    - master
    - main
    - '*.x'
  pull_request:
    branches:
    - master
    - main
    - '*.x'

jobs:
  visual-regression-test:
    name: Visual Regression Tests ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Print basic Python info
      shell: python
      run: |
        import sys
        print(sys.executable, sys.version, sep='\n')
    - name: Install docrepr
      run: python -m pip install --upgrade .[test,visual_test]
    - name: List packages in environment
      run: pip list
    - name: Install Firefox
      run: python -m playwright install firefox
    - name: Run tests
      shell: bash
      run: python -I -bb -X dev -W error -m pytest --compare-screenshots --asyncio-mode=auto
    - name: Upload UI test artifacts
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: visual-regression-test-output
        path: |
          docrepr/tests/reference_screenshots/**
          docrepr/tests/screenshots/**
          docrepr/tests/diffs/**
